version: '3.8'

services:
  tghbot_app:
    build: .
    container_name: tghbot_container
    env_file:
      - config.env
    ports:
      - "80:80"
    volumes: 
      - ./tghbot:/usr/src/app/tghbot
    command: python /usr/src/app/update.py
