version: '3.8'

services:
  tghbot_app:
    build: .
    container_name: tghbot_container
    env_file:
      - config.env
    ports:
      - "80:80"
    volumes:
            - ./plugins:/usr/src/app/plugins
      - ./sabnzbdapi:/usr/src/app/sabnzbdapi
      - ./tghbot:/usr/src/app/tghbot
    command: python ./update.py
