services:
  app:
    container_name: tghbot
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    ports:
      - "80:80"
      - "8060:8060"
      - "4000:4000"
      - "4090:4090"
